# -*- coding: utf-8 -*-
"""proje2Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsZNz1_Y3TUQTm1CCbCFc6DZRJnAwNfm
"""

import pandas as pd
import numpy as np
import matplotlib as plt

dataRead = pd.read_csv("NetflixOriginals.csv",encoding="ISO-8859-1")
dataRead

language=dataRead["Language"]
listDil = []
for deger in language:
  listDil.append(deger)

listDil.sort()
print(listDil)
print("\n\n")

tumKelimeler={}
for kelime in listDil:
    if kelime not in tumKelimeler:
        tumKelimeler[kelime] = 1
    else:
        tumKelimeler[kelime] += 1

for sayma in tumKelimeler.keys():
   print ("Kelime: %s =====%s " %(sayma , tumKelimeler[sayma]))



language=dataRead["Language"]
list = set(language)

#en cok kullanılan 3 dil
sayiDil=len(set(tumKelimeler.values()))
sayici = 0
enBuyukIsimSayi = 0
SayiListe = []

for i in range(sayiDil):
  SayiListe.append(i)


for islemSayi in range(3):
  for karsilastirmaSayi in SayiListe:
      enBuyukIsimSayi = max(SayiListe)


  print("\nEn Buyuk Degere Sahip Sayi:     ",enBuyukIsimSayi)

  degerSirasiListe = SayiListe.index(enBuyukIsimSayi)
  print("En Buyuk Değere Sahip Sayının Sırası:   ",degerSirasiListe)
  print("\n")
  SayiListe.pop(degerSirasiListe)

#IMDB Puanı Yuksek ilk 10 Film Bilgisi
IMDB_Score = dataRead["IMDB Score"]
IMDB_Title = dataRead["Title"]



filmScore = []
for degerPuan in IMDB_Score:
  filmScore.append(degerPuan)
print(filmScore)

filmTitle = []
for degerTitle in IMDB_Title:
  filmTitle.append(degerTitle)
print(filmTitle)


enBuyukSayi = 0


for islemSayi in range(10):
  enBuyukSayi = max(filmScore)
  print("\nEn Buyuk Degere Sahip IMDB Degeri:     ",enBuyukSayi)
  degerSirasiIMDB = filmScore.index(enBuyukSayi)
  print("En Cok IMDB Puanına Sahip Filmin Ismi:   ", filmTitle[degerSirasiIMDB])
  print("\n")
  filmScore.remove(enBuyukSayi)

dilListesi = []
for deger in list:
  dilListesi.append(deger)

dilListesi.sort()
print(dilListesi)

genre=dataRead["Genre"]
listGenre = set(genre)
genreListesi = []
for degerGenre in listGenre:
  genreListesi.append(degerGenre)

genreListesi.sort()
print("Genre Sütununa Ait Veriler:  ",genreListesi)

genreSayi = len(genreListesi)
print("Genre Sütununa Ait Tür Sayısı:  ",genreSayi)
#genre bilgisi icin gorsellestirme yapamadim

#IMDB puanı ve Runtime Arası Korelasyon
import seaborn as sns

IMDB_Puan_Korelasyon = dataRead["IMDB Score"]
Korelasyon_RUNTIME = dataRead["Runtime"]

filmPuanKorelasyon = []
for degerPuanIMDB in IMDB_Puan_Korelasyon:
  filmPuanKorelasyon.append(degerPuanIMDB)
print(filmPuanKorelasyon)

print("\n")

RuntimeKorelasyon = []
for degerRuntime in Korelasyon_RUNTIME:
  RuntimeKorelasyon.append(degerRuntime)
print(RuntimeKorelasyon)

tabloVeri = pd.read_csv("NetflixOriginals.csv",encoding="ISO-8859-1",index_col=0)
sns.lmplot(x='Runtime', y='IMDB Score', data=tabloVeri)

#IMDB Puanı Yuksek ilk 10 Genre Bilgisi
IMDB_Score = dataRead["IMDB Score"]
IMDB_Genre = dataRead["Genre"]



filmScore = []
for degerPuan in IMDB_Score:
  filmScore.append(degerPuan)
print(filmScore)

filmGenre = []
for degerGenre in IMDB_Genre:
  filmGenre.append(degerGenre)
print(filmGenre)


enBuyukSayi = 0


for islemSayi in range(11):
  enBuyukSayi = max(filmScore)
  print("\nEn Buyuk Degere Sahip IMDB Degeri:     ",enBuyukSayi)
  degerSirasiIMDB = filmScore.index(enBuyukSayi)
  print("En Cok IMDB Puanına Sahip Filmin Ismi:   ", filmGenre[degerSirasiIMDB])
  print("\n")
  filmScore.remove(enBuyukSayi)

#gorsellestirme yapamadım